# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-06 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('price', '0002_userprofile_cardid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cardID',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
    ]
